mdk/commands/tracker.py

Was using addLabels instead of removeLabels in the list test causing an exception.

Correct removeLabels checks

---

mdk/scripts/dev.php
mdk/scripts/undev.php

See https://tracker.moodle.org/browse/MDL-48559

Disable cronclionly in dev.php

---

mdk/tools.py

Generic function - useful for any text, not just comments (summary, description, testing instructions, etc).
Takes (optional) existing file *content* to play with

Function to launch the editor for the purposes of getting new text content

---

scripts/version.php

This will check to see if there are any plugins that have
a status of downgraded (The version number of the old plugin is
higher than the new one). Then it will change the version number
in the config_plugin table.

Script for downgrading moodle plugins

---

mdk/commands/precheck.py

See MDLSITE-4414 https://github.com/moodlehq/moodle-local_ci/pull/72
(Note this precheck isn't idealy suited - it won't report a problem when
checks are in progress - which will be likely for many MDK users as they
will likely push shortly before precheck)

Be aware of Travis in the prechecker output

---

mdk/scripts/external_functions.php

These change is needed to get the external functions updated

External update services needed

---

mdk/scripts/random-users.php

Also will fix an incomplete admin user from a new install.

New random-users script will generate random users from randomuser.me

---

mdk/commands/precheck.py

MDLSITE-4770 introduced a new mustache precheck

Add mustache to mdk precheck

---

mdk/config-dist.json

Hi Fred, please feel free to pull this. Thanks!

Prepare for Moodle 3.4 development

---

.gitignore
CHANGELOG.rst
mdk/config-dist.json
mdk/version.py

Hi Fred, please feel free to pull this.
I also another commit that adds the ".idea" folder to .gitignore for plebs like me who use PyCharm IDE. Hope this is alright.
Thanks!

Prepare Moodle for 3.5 development

---

README.rst
mdk/commands/create.py
mdk/commands/install.py
mdk/config-dist.json
mdk/db.py
requirements.txt

Since Moodle officially supports SQL Server and with docker making running SQL Server easier even on Linux nowadays, I think it would be nice if MDK would also be able to support creation/installation of Moodle instances running with the SQL Server database.

Support SQL Server

---

extra/bash_completion
mdk/commands/plugin.py
mdk/moodle.py
mdk/plugins.py

This will remove the directory and files as well.

Add the option of uninstall for the plugin command.

---

mdk/jira.py

Fix TypeError when downloading patch file on python3

---

mdk/git.py
mdk/moodle.py

See
https://github.blog/2021-09-01-improving-git-protocol-security-github/#no-more-unauthenticated-git
for more information on this change

Rewrite git://github.com URLs as https://github.com

---

mdk/commands/push.py

Fixes a regression introduced by #208

Import yesOrNo into mdk push

---

mdk/config-dist.json

- Create a 401 branch
- Change masterBranch to 402

Update for Moodle 4.2 development

---

mdk/commands/fix.py

Do not ask about master branch if a main branch exists

---

mdk/plugins.py

Currently `mdk plugin install` fails for the 4.X branches, because the script looks for a plugin available for 4.02 (derived from branch name 402).
This PR fixes the problem for all versions.

Correctly calculate plugin version from branch

---

mdk/workplace.py

Check and create cached clones before using it

---

mdk/commands/behat.py
mdk/config-dist.json

Add an option to allow user to use the new Selenium Grid

Feature: Add ability to use new Selenium Grid

---

mdk/moodle.py
mdk/scripts/version.php

This set of changes adds a new `Moodle.getVersionPath(path)` method which looks at the specified path and looks for the path to `version.php` based on either the current location, or the location after MDL-83424 lands.

Support Moodle with MDL-83424 applied
