FMCorz/mdk

- mdk/scripts/undev.php
I keep getting:
PHP Notice:  Undefined property: stdClass::$requiremodintro in .../moodle/mdkscriptrun.php on line 104
Notice: Undefined property: stdClass::$requiremodintro in .../moodle/mdkscriptrun.php on line 104
PHP Fatal error:  Call to a member function get_defaultsetting() on a non-object in .../moodle/mdkscriptrun.php on line 104
Fatal error: Call to a member function get_defaultsetting() on a non-object in .../moodle/mdkscriptrun.php on line 104
When running undev. This seems to do the trick
> Check for requiremodintro before attempting to set it to default

- mdk/scripts/users.php
I occasionally get weird problems when using the mdk generated accounts because their emails do not validate correctly. Example.com was created for this purpose. Alternatively perhaps we could use @test.moodle.org
I understand if it's better to use localhost for the sake of email debugging. Personally I use mailcatcher which catches all outbound emails, so sending them off to example.com isn't a problem for me. Just making this patch to throw the idea out there.
> Use example.com for email addresses

- mdk/commands/precheck.py
In https://github.com/moodlehq/moodle-local_ci/pull/70 the php code sniffer abbreviation was changed to phpcs. In various other isues we've added more CI checks which are missing from mdk.
Ideally this should be rewritten to output the result of all the checks, regardless of whether they are defined in mdk, but thats for another day.
> Fix precheck command after phpcs renaming and add missing checks.

- mdk/commands/behat.py
Behat 3.x expect format and out parameters to be
one after other and doesn't support concatenation
> Fix #129: Add support for Behat 3.x formatter

- mdk/config-dist.json
We are going to disable http requests at some point soon, this will break mdk ci
> MDLSITE-4668 integration.moodle.org has moved to https

- mdk/commands/behat.py
All behat directories will be created within
$CFG->behat_dataroot, so parallel and single
runs can be handled and it doesn't pollute
user host system
> Behat path has been modified since Moodle 3.2.2 MDL_54628

- mdk/db.py
- mdk/moodle.py
Knowing that you like to keep mdk backwards compatible with earlier Moodle versions, it was fun (tricky) to find a clean way to pass through the branch information to DB. I chose 31 as the branch to do this from, but I can understand why you would choose 33 instead.
Fixes #152
> Switch to using wide utf8 byte characters in MySQL install

- mdk/config-dist.json
- mdk/scripts/setupsecurity.sh
Hi Fred,
I am not sure if you have access, but we discussed this proposal in https://tracker.moodle.org/browse/HQ-1429.
To resume a bit the PR; in a near future we will need minor release weeks' testing against the security repository instead of against integration.git. One of the advantages that we seek moving security issues to a security repository is to prevent security patches to be released to the public days before a minor release. Even if testing happens against security.git it is likely that at some point we (devs) make mistakes and push security patches to github; one of possible scenarios is that I am the assignee of an issue that is failing and I need to patch it. We should prevent devs pushing those branches to github and instead upload patch files to tracker.
> New script to set up a clone for testing against the security repo.

- mdk/commands/precheck.py
With the "debug" level set to "WARNING" (which seems reasonable value
for normal usage), the URL was not displayed before.
Fixes issue #158
> Always display URL of the failed precheck job regardless the debug level

- mdk/jira.py
From time to time I am running into troubles with my local keyring installation. I am not sure what was the original intention but I think it is valid to warn the user if the keyring module can't be loaded - especially given it is enlisted among requirements.
> Warn the user if the keyring module can't be loaded

- CHANGELOG.rst
- mdk/db.py
- mdk/version.py
When I tried to create an instance running on sqlsrv, I got the following:
> AttributeError: 'NoneType' object has no attribute 'execute'
This is because I accidentally nuked the assignment of sqlsrv's cursor to self.cur in my previous patch.
Created a patch for this, with a version bump commit as well. Hope this is okay. Thanks!
> Missing assignment for the sqlsrv cursor

- mdk/ci.py
- requirements.txt
After a recent upgrade of HQ CI Jenkins, the mdk precheck stopped working.
> Make mdk precheck work again

- mdk/config-dist.json
- mdk/phpunit.py
I often make use of the buildcomponentconfigs feature allowing me to run all unit tests for the given component, such as
vendor/bin/phpunit -c mod/workshop/
To be able to do so, I have to manually run `admin/tool/phpunit/cli/util.php --buildcomponentconfigs` every time. It makes sense to let mdk do it automatically.
Adding this feature was already discussed with @FMCorz at https://moodle.org/local/chatlogs/index.php?conversationid=19150#c605808 who has alternate way to achieve the same. However, I fail to remember that one. Also, there are cases when I simply run the phpunit manually without mdk.
So I still think it is worth considering to add this as an option, enabled by default as it does not hurt.
Further references: https://moodle.org/local/chatlogs/index.php?q=buildcomponentconfigs
> Automatically build distributed phpunit.xml files for each component

- CHANGELOG.rst
- mdk/config-dist.json
- mdk/db.py
- mdk/version.py
The driver for the sqlsrv connection string is currently hardcoded to 'ODBC Driver 13 for SQL Server'. This might not always be the case (e.g. updated mssql-tools in Ubuntu 16.04 now use 'ODBC Driver 17 for SQL Server').
So it's more proper to detect whether the installed ODBC driver and use the installed driver's name. If it's not installed, throw an exception and point devs to the docs URL to help them get started if they're not familiar about setting up ODBC drivers for SQL Server.
> Detect which SQL Server Driver is installed

- mdk/scripts/version.php
I usually had to purge caches manually after switching branch to make
mdk's version.php aware of the version number mismatch. Resetting the
config cache at the beginning of the script should help to avoid this.
The patch also makes use of the plugin manager's API to reset its
own caches.
> Invalidate config caches prior reading plugin versions

- mdk/scripts.py
The `os.path.splitext()` already returns the extension with the leading
dot. So it was creating files like `mdkscriptrun..sh` with the extra dot
in the name. The patch removes the extra dot.
> Do not use an extra dot in the mdkscriptrun script

- mdk/config-dist.json
- mdk/moodle.py
When reviewing contributed plugins and patches, it sometimes happens that the developer puts hard-coded table name into their SQL queries by mistake, such as
```
$sql = "SELECT id, foo, bar FROM mdl_foo_bar";
```
instead of the correct one
```
$sql = "SELECT id, foo, bar FROM {foo_bar}";
```
As most of the sites are using the default `mdl_` table name prefix, this kind of bugs may be hard to be spotted. It will help if the reviewer/tester has a custom non-default table name prefix set while testing the plugins and patches. Thanks in advance for considering it.
> Add ability to define custom $CFG->prefix for new instances

- mdk/scripts/dev.php
- mdk/scripts/mindev.php
- mdk/scripts/undev.php
It's a new setting for 3.8 which enables the caching of templates in
order to improve page loading performance for production sites. Although
on dev, this setting should be disabled.
> Set cachetemplates config value for dev/undev scripts

- mdk/commands/phpunit.py
- mdk/phpunit.py
It would be great to add support for PHPUnit's --repeat argument in
order to run tests repeatedly which is useful for testing random
PHPUnit errors.
> Add support for repeating tests

- mdk/db.py
Python processes all top-level imports regardless of whether or not they are used. This fix allows the use of MDK on systems where not all of the database libraries are available.
> Fix Python importing unused database libraries

- mdk/config-dist.json
- mdk/moodle.py
In order to make Behat running in my environment, I have to set the `behat_profiles` in my config.php. However, every time I re-install an MDK instance, I loose that setting and have to add it back to the new config.php. To avoid that, I would like to add the `behat_profiles` (and also `behat_parallel_run` which I also often define) into the `forceCfg`. However, at the moment, only strings and integer values are supported there.
This pull request adds support for non-scalar values - dictionaries (associative arrays) and lists (non-associative arrays) - in the `forceCfg`.
> Allow forceCfg to also set a non-scalar value such as behat_profiles

- mdk/commands/behat.py
Without decoding the API response, running mdk behat without Selenium
already installed would crash, due to regex not supporting string
matches against bytes-like objects.
> Decode Selenium API response to string to prevent regex TypeError

- mdk/scripts/dev.php
Without declaring $DB as a global variable in config.php (similarly to
how it is done for $CFG), the PHPUnit raises
Notice: Undefined variable: DB in {...}/config.php on line 44
> Avoid PHP Notice "Undefined variable: DB" in PHPUnit setup

- mdk/commands/init.py
Hi @junpataleta and/or @FMCorz 
I've had troubles creating my first instance, because Git was set (initially) false for my environment. After I made some research on this toolkit and found out that this path is specified in the config file. For sure, for more than 90% of cases, it will work out of the box.
So I had the idea, why we don't ask that in the initialization as it's a requirement. What do you think about my proposed code/solution/idea?
Cheers
Adrian
> Specify Git path during initialization

- mdk/commands/tracker.py
- mdk/jira.py
Add ability to open current jira issue in default web browser: `mdk tracker --open`
> feature: open jira ticket in default browser

- mdk/scripts/jsconfig.php
This patch adds a new script for vscode to generate a jsconfig.json file.
This file is described at
https://code.visualstudio.com/docs/languages/jsconfig and can be used to configure vscode and other similar editors to understand our module loading.
> Add vscode script to generate jsconfig.json

- mdk/config-dist.json
See https://github.blog/2018-05-01-ignore-white-space-in-code-review/ for more information.
> Make use of GitHub whitespace ignore parameter in push URLs

- mdk/commands/behat.py
- mdk/commands/phpunit.py
This option was deprecated in Composer 2 and will be removed in Composer 3.
> Remove --dev arg from composer install

- mdk/commands/backport.py
- mdk/commands/create.py
- mdk/commands/rebase.py
- mdk/tools.py
With the version format changes starting 3.10, the version options have included non-existent versions. This adds a utility function for generating the version options that match the actual released versions of Moodle.
> Add tool.version_options

- mdk/commands/create.py
- mdk/commands/fix.py
- mdk/commands/plugin.py
- mdk/commands/push.py
- mdk/commands/rebase.py
- mdk/config-dist.json
- mdk/jira.py
- mdk/moodle.py
- mdk/tools.py
- mdk/workplace.py
Additional notes:
- `DoctorCommand.masterbranch` has been renamed to `DoctorCommand.mainbranch` but the `--masterbranch` argument is retained (for now).
See https://tracker.moodle.org/browse/MDLSITE-7418 for more information.
> Replace references of `master` with `main`

- mdk/scripts/undev.php
From 4.4, the settings in the `themesettings` section have been moved to `themesettingsadvanced`.
This patch adds the fetching of the theme settings from the new `themesettingsadvanced` section to support 4.4 and up but falls back to `themesettings` to support 4.3 and below.
See https://tracker.moodle.org/browse/MDL-78426.
> Update theme settings location for 4.4 and up.

- requirements.txt
For Python 3.11 and later,
We need `setuptools` package, other the `mdk create` command cannot be executed
> Python 3.11 and 3.12 compatibility changes

- mdk/tools.py
With the `master` branch gone, there is no need to fall back to it. Otherwise, errors will be encountered, especially when MDK is freshly installed.
For example:
```bash
$ mdk create -t
Creating instance integration_main...
Cloning integration repository into cache...
The main branch has not been found, using master instead.
Cloning repository...
Checking out branch...
Error creating integration_main:
This is not a Git repository
Traceback (most recent call last):
File "/home/moodle/apps/mdk/mdk/commands/create.py", line 172, in do
M = self.Wp.create(**kwargs)
File "/home/moodle/apps/mdk/mdk/workplace.py", line 181, in create
repo.delRemote('origin')
File "/home/moodle/apps/mdk/mdk/git.py", line 116, in delRemote
result = self.execute(cmd)
File "/home/moodle/apps/mdk/mdk/git.py", line …
```
> Remove fallback logic to `master`

- mdk/scripts.py
When executing custom shell commands (*.sh), I was getting an error:
Error while running the script on [...]
'str' object has no attribute 'is_absolute'
The patch makes sure that the Path instance is passed as expected by the container methods.
> Use Path instance as argument for container commands

- mdk/fetch.py
This is a fix for https://github.com/FMCorz/mdk/issues/245:
The exception is looking for 1 argument but receives 2.
> Issue 245: correct number of placeholders for expected strings

- mdk/commands/rebase.py
This is a fix for issue #247:
The function call was surrounded by quotes and made into a string.
> Issue 247: fixed version_options() syntax

- mdk/scripts/version.php
The `version.php` is still in the `$CFG->dirroot`
> Remove an overly-zealous support for MDL-83424

- extra/goto_instance
I am informed that some people create their own symlink for Moodle to link straight to the `public` directory. As a result though the `gt` command points to the wrong place.
Rather than having `gt` point to the public directory, this changes it to point to the storage directory behind the normal symlink.
> Update gt to link to the moodle root
